# used by local ft to make requests to wiremock
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9000/realms/groot-mg
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 5000 # 5s for database timeout

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka