server:
  port: 8082
  servlet:
    contextPath: /sales-catalog

spring:
  jmx:
    enable: false
  application:
    name: sales-catalog
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/${KEYCLOAK_REALM:shopping-api}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_URL:localhost:5432}/postgres?currentSchema=groot_mg
    username: ${POSTGRESQL_USERNAME:sales_catalog_user}
    password: ${POSTGRESQL_PASSWORD:sales_catalog_pass}
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /private
      exposure.include: info,health,prometheus
      path-mapping.prometheus: /metrics
  info:
    java:
      enabled: true
  health:
    diskspace:
      enabled: false

springdoc:
  packagesToScan: org.springframework.boot.actuate.endpoint, com.generoso.salescatalog.controller, com.generoso.salescatalog.converter
#  packagesToExclude: com.generoso.salescatalog.entity
  api-docs:
    path: /private/api-docs
  show-actuator: true
  swagger-ui:
    path: /private/swagger

#logging:
#  level:
#    reactor.netty: INFO
#    org.springframework.security: TRACE
#    org.springframework.web: DEBUG