server:
  port: 8082
  servlet:
    contextPath: /shopping-api

spring:
  application:
    name: shopping-api
  profiles:
    active: local
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/shopping}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
    platform: postgres
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1

  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /private
      exposure.include: health,info,prometheus
      path-mapping.prometheus: /metrics
  info:
    java:
      enabled: true
  health:
    diskspace:
      enabled: true
    db:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_HOST:http://localhost:8081/eureka}
    register-with-eureka: true