version: '3.8'
services:
  database:
    container_name: spring-app-database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spring_crud
    ports:
      - "5432:5432"

#  pgadmin:
#    container_name: spring-app-pgadmin4
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"

  app:
    container_name: spring-app
    build: spring-crud-api
    restart: always
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - database
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DATASOURCE_URL=jdbc:postgresql://database:5432/spring_crud
      - DATASOURCE_USERNAME=root
      - DATASOURCE_PASSWORD=root

  prometheus:
    container_name: spring-app-prometheus
    image: prom/prometheus:latest
    ports:
      - 9191:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
