version: '3.8'

services:
  database:
    container_name: sales-catalog-database
    build: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sales-catalog
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/backup:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d shopping -U root" ]
      interval: 5s
      timeout: 5s
      retries: 5

#  pgadmin:
#    container_name: sales-catalog-pgadmin4
#    image: dpage/pgadmin4:6.8
#    restart: unless-stopped
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"
#    depends_on:
#      database:
#        condition: service_healthy

  postgres-exporter:
    container_name: postgres-exporter
    image: prometheuscommunity/postgres-exporter:v0.10.1
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://root:root@database:5432/sales-catalog?sslmode=disable"
    links:
      - database
      - prometheus
    depends_on:
      database:
        condition: service_healthy

  sales-catalog:
    container_name: sales-catalog
    build: sales-catalog-app
    restart: always
    ports:
      - "8082:8082"
      - "5005:5005"
    depends_on:
      database:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DATASOURCE_URL=jdbc:postgresql://database:5432/sales-catalog
      - DATASOURCE_USERNAME=root
      - DATASOURCE_PASSWORD=root

      # Include wiremock to mock eureka server for local
      #- EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8081/eureka/