version: '3.8'

services:
  database:
    container_name: shopping-app-database
    build: postgresql
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shopping
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/backup:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d shopping -U root" ]
      interval: 5s
      timeout: 5s
      retries: 5

#  pgadmin:
#    container_name: shopping-app-pgadmin4
#    image: dpage/pgadmin4:6.8
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"
#    depends_on:
#      database:
#        condition: service_healthy

  postgres-exporter:
    container_name: postgres-exporter
    image: prometheuscommunity/postgres-exporter:v0.10.1
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://root:root@database:5432/shopping?sslmode=disable"
    links:
      - database
      - prometheus
    depends_on:
      database:
        condition: service_healthy

  app:
    container_name: shopping-api
    build: shopping-api
    restart: always
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DATASOURCE_URL=jdbc:postgresql://database:5432/shopping
      - DATASOURCE_USERNAME=root
      - DATASOURCE_PASSWORD=root

  prometheus:
    container_name: shopping-app-prometheus
    build:
      context: prometheus
      args:
        ENVIRONMENT: local
    restart: unless-stopped
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  alertmanager:
    container_name: shopping-app-alertmanager
    build:
      context: alertmanager
      args:
        ENVIRONMENT: local
    restart: unless-stopped
    ports:
      - "9093:9093"
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml

  # default user and password: admin
  grafana:
    container_name: shopping-app-grafana
    image: grafana/grafana:8.5.2
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
