spring:
  jmx:
    enable: false
  application:
    name: gateway
server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    fetch-registry: true
    register-with-eureka: false

zuul:
  sensitive-headers: Cookie

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /private
      exposure.include: info,health,prometheus
      path-mapping.prometheus: /metrics
  info:
    java:
      enabled: true
  health:
    diskspace:
      enabled: true
    db:
      enabled: true