global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/rules/common/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
  - job_name: shopping-api
    scrape_interval: 5s
    metrics_path: /shopping-api/private/metrics
    static_configs:
      - targets:
          - shopping-api:8082
  - job_name: postgres-exporter
    static_configs:
      - targets:
        - postgres-exporter:9187
  - job_name: service-discovery
    scrape_interval: 5s
    metrics_path: /private/metrics
    static_configs:
      - targets:
          - service-discovery:8081