# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Test All Modules

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Building Service Discovery module
      run: ./gradlew --no-daemon :service-discovery:build
    - name: Building Gateway module
      run: ./gradlew --no-daemon :gateway:build
    - name: Building Shopping lib module
      run: ./gradlew --no-daemon :shopping-lib:build
    - name: Building Shopping API module
      run: ./gradlew --no-daemon :shopping-api:build
  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Testing Shopping lib module
      run: ./gradlew --no-daemon :shopping-lib:test
    - name: Testing Shopping API module
      run: ./gradlew --no-daemon :shopping-api:test
