server:
  servlet:
    contextPath: /spring-crud

spring:
  profiles:
    active: local
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/spring_crud}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
    platform: postgres
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1

  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

management:
  endpoints:
    web:
      base-path: /private
      exposure.include: health,info,prometheus
      path-mapping.prometheus: /metrics
  info:
    java:
      enabled: true